name: deploy
authore: SooYoung
description: "Use deploy module in github action"
inputs:
  KUBECTL_VERSION:
    description: "set kubectl version"
    required: false
    default: "latest"
  HELM_VERSION:
    description: "set helm version"
    required: false
    default: v3.11.1
  CLUSTER_NAME:
    description: "set cluster name"
    required: true
    default: "github-actions"
  RELEASE_NAME:
    description: "set release_name"
    required: true
    default: "my-app"
  HELM_CHART_PATH:
    description: "set helm chart path"
    required: true
    default: "kubernetes/my-app"
  NAMESPACE:
    description: "set namespace"
    required: true
    default: "my-app-dev"
  REPOSITORY:
    description: "set ecr registry/repository"
    required: true
    default: ""

runs:
  using: "composite"
  steps:
    - name: setup kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: ${{ inputs.KUBECTL_VERSION }}
    - name: setup helm
      uses: azure/setup-helm@v3
      with:
        version: ${{ inputs.HELM_VERSION }}
    - name: access Kubernetes
      shell: bash
      run: |
        aws eks update-kubeconfig --name ${{ inputs.CLUSTER_NAME }}
    - name: deploy
      shell: bash
      run: |
        helm upgrade --install ${{ inputs.RELEASE_NAME }} ${{ inputs.HELM_CHART_PATH }} --create-namespace --namespace ${{ inputs.NAMESPACE }} \
        --set image.tag=${{ github.sha }} \
        --set image.repository=${{ inputs.REPOSITORY }}
